Fix missing return type annotation for tarpit_client reported by mypy
fastapi_tarpit/tarpit.py:94: error: Function is missing a return type annotation  [no-untyped-def]