Add missing type annotation to kwargs
fastapi_tarpit/tarpit.py:132: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]