Fix missing return type annotation in example.py reported by mypy
example/example.py:16: error: Function is missing a return type annotation  [no-untyped-def]